// Supported target languages
const supportedLanguages = { pl: "Polnisch" };

// Vocabulary dataset
const lessons = {
  seasons_months_weekdays: {
    labelDe: "Jahreszeiten, Monate & Wochentage",
    pairs: [
      // === Jahreszeiten (4 Paare) ===
      { de: "Frühling", pl: "wiosna" },
      { de: "Sommer",   pl: "lato"   },
      { de: "Herbst",   pl: "jesień" },
      { de: "Winter",   pl: "zima"   },
      
      // === Monate (12 Paare) ===
      { de: "Januar",    pl: "styczeń"    },
      { de: "Februar",   pl: "luty"       },
      { de: "März",      pl: "marzec"     },
      { de: "April",     pl: "kwiecień"   },
      { de: "Mai",       pl: "maj"        },
      { de: "Juni",      pl: "czerwiec"   },
      { de: "Juli",      pl: "lipiec"     },
      { de: "August",    pl: "sierpień"   },
      { de: "September", pl: "wrzesień"   },
      { de: "Oktober",   pl: "październik"},
      { de: "November",  pl: "listopad"   },
      { de: "Dezember",  pl: "grudzień"   },

      // === Wochentage (7 Paare) ===
      { de: "Montag",     pl: "poniedziałek" },
      { de: "Dienstag",   pl: "wtorek"       },
      { de: "Mittwoch",   pl: "środa"        },
      { de: "Donnerstag", pl: "czwartek"     },
      { de: "Freitag",    pl: "piątek"       },
      { de: "Samstag",    pl: "sobota"       },
      { de: "Sonntag",    pl: "niedziela"    }
    ]
  },
  numbers_up_to_20: {
    labelDe: "Zahlen bis 20",
    pairs: [
      { de: "eins", pl: "jeden" },
      { de: "zwei", pl: "dwa" },
      { de: "drei", pl: "trzy" },
      { de: "vier", pl: "cztery" },
      { de: "fünf", pl: "pięć" },
      { de: "sechs", pl: "sześć" },
      { de: "sieben", pl: "siedem" },
      { de: "acht", pl: "osiem" },
      { de: "neun", pl: "dziewięć" },
      { de: "zehn", pl: "dziesięć" },
      { de: "elf", pl: "jedenaście" },
      { de: "zwölf", pl: "dwanaście" },
      { de: "dreizehn", pl: "trzynaście" },
      { de: "vierzehn", pl: "czternaście" },
      { de: "fünfzehn", pl: "piętnaście" },
      { de: "sechzehn", pl: "szesnaście" },
      { de: "siebzehn", pl: "siedemnaście" },
      { de: "achtzehn", pl: "osiemnaście" },
      { de: "neunzehn", pl: "dziewiętnaście" },
      { de: "zwanzig", pl: "dwadzieścia" }
    ]
  },
  adjectives_opposites: {
    labelDe: "Eigenschaften & Gegensätze",
    pairs: [
      { de: "groß", pl: "duży" },
      { de: "klein", pl: "mały" },
      { de: "schnell", pl: "szybki" },
      { de: "langsam", pl: "wolny" },
      { de: "gut", pl: "dobry" },
      { de: "schlecht", pl: "zły" },
      { de: "neu", pl: "nowy" },
      { de: "alt", pl: "stary" },
      { de: "jung", pl: "młody" },
      { de: "schön", pl: "ładny" },
      { de: "hässlich", pl: "brzydki" },
      { de: "heiß", pl: "gorący" },
      { de: "kalt", pl: "zimny" },
      { de: "warm", pl: "ciepły" },
      { de: "nah", pl: "bliski" },
      { de: "weit", pl: "daleki" },
      { de: "lang", pl: "długi" },
      { de: "kurz", pl: "krótki" },
      { de: "hoch", pl: "wysoki" },
      { de: "niedrig", pl: "niski" },
      { de: "teuer", pl: "drogi" },
      { de: "billig", pl: "tani" },
      { de: "schwer (Gewicht)", pl: "ciężki" },
      { de: "leicht (Gewicht)", pl: "lekki" },
      { de: "schwierig", pl: "trudny" },
      { de: "einfach", pl: "łatwy" },
      { de: "sauber", pl: "czysty" },
      { de: "schmutzig", pl: "brudny" },
      { de: "voll", pl: "pełny" },
      { de: "leer", pl: "pusty" }
    ]
  },
  possessive_pronouns: {
    labelDe: "Possessivpronomen",
    pairs: [
      { de: "mein (m)", pl: "mój" },
    { de: "meine (f)", pl: "moja" },
    { de: "mein (n)", pl: "moje" },
    { de: "dein (m)", pl: "twój" },
    { de: "deine (f)", pl: "twoja" },
    { de: "dein (n)", pl: "twoje" },
    { de: "sein (m/n)", pl: "jego" },
    { de: "ihr (Sg.)", pl: "jej" },
    { de: "unser (m)", pl: "nasz" },
    { de: "unsere (f)", pl: "nasza" },
    { de: "unser (n)", pl: "nasze" },
    { de: "euer (m)", pl: "wasz" },
    { de: "eure (f)", pl: "wasza" },
    { de: "euer (n)", pl: "wasze" },
    { de: "ihr (Pl. - deren)", pl: "ich" },
    { de: "Ihr (formell, Herr)", pl: "Pana" },
    { de: "Ihr (formell, Frau)", pl: "Pani" },
    { de: "Ihr (formell, Plural)", pl: "Państwa" },
      { de: "ihr / Ihr (Pl.)", pl: "ich" },
      { de: "sein/ihr eigenes (m)", pl: "swój" },
      { de: "sein/ihr eigenes (f)", pl: "swoja" },
      { de: "sein/ihr eigenes (n)", pl: "swoje" }
    ]
  },
  basic_verbs_1: {
    labelDe: "Grundverben I (Konjugationen)",
    pairs: [
      { de: "ich bin (sein)", pl: "ja jestem" },
      { de: "du bist", pl: "ty jesteś" },
      { de: "er/sie/es ist", pl: "on/ona/ono jest" },
      { de: "wir sind", pl: "my jesteśmy" },
      { de: "ihr seid", pl: "wy jesteście" },
      { de: "sie/Sie sind", pl: "oni/one są" },
      
      { de: "ich habe (haben)", pl: "ja mam" },
      { de: "du hast", pl: "ty masz" },
      { de: "er/sie/es hat", pl: "on/ona/ono ma" },
      { de: "wir haben", pl: "my mamy" },
      { de: "ihr habt", pl: "wy macie" },
      { de: "sie haben", pl: "oni/one mają" },
      
      { de: "ich mache (machen)", pl: "ja robię" },
      { de: "du machst", pl: "ty robisz" },
      { de: "er/sie/es macht", pl: "on/ona/ono robi" },
      { de: "wir machen", pl: "my robimy" },
      { de: "ihr macht", pl: "wy robicie" },
      { de: "sie machen", pl: "oni/one robią" },
      
      { de: "ich gehe (gehen)", pl: "ja idę" },
      { de: "du gehst", pl: "ty idziesz" },
      { de: "er/sie/es geht", pl: "on/ona/ono idzie" },
      { de: "wir gehen", pl: "my idziemy" },
      { de: "ihr geht", pl: "wy idziecie" },
      { de: "sie gehen", pl: "oni/one idą" },
      
      { de: "ich esse (essen)", pl: "ja jem" },
      { de: "du isst", pl: "ty jesz" },
      { de: "er/sie/es isst", pl: "on/ona/ono je" },
      { de: "wir essen", pl: "my jemy" },
      { de: "ihr esst", pl: "wy jecie" },
      { de: "sie essen", pl: "oni/one jedzą" },
      
      { de: "ich trinke (trinken)", pl: "ja piję" },
      { de: "du trinkst", pl: "ty pijesz" },
      { de: "er/sie/es trinkt", pl: "on/ona/ono pije" },
      { de: "wir trinken", pl: "my pijemy" },
      { de: "ihr trinkt", pl: "wy pijecie" },
      { de: "sie trinken", pl: "oni/one piją" },
      
      { de: "ich spreche (sprechen)", pl: "ja mówię" },
      { de: "du sprichst", pl: "ty mówisz" },
      { de: "er/sie/es spricht", pl: "on/ona/ono mówi" },
      { de: "wir sprechen", pl: "my mówimy" },
      { de: "ihr sprecht", pl: "wy mówicie" },
      { de: "sie sprechen", pl: "oni/one mówią" },
      
      { de: "ich weiß (wissen)", pl: "ja wiem" },
      { de: "du weißt", pl: "ty wiesz" },
      { de: "er/sie/es weiß", pl: "on/ona/ono wie" },
      { de: "wir wissen", pl: "my wiemy" },
      { de: "ihr wisst", pl: "wy wiecie" },
      { de: "sie wissen", pl: "oni/one wiedzą" },
      
      { de: "ich sehe (sehen)", pl: "ja widzę" },
      { de: "du siehst", pl: "ty widzisz" },
      { de: "er/sie/es sieht", pl: "on/ona/ono widzi" },
      { de: "wir sehen", pl: "my widzimy" },
      { de: "ihr seht", pl: "wy widzicie" },
      { de: "sie sehen", pl: "oni/one widzą" },
      
      { de: "ich will (wollen)", pl: "ja chcę" },
      { de: "du willst", pl: "ty chcesz" },
      { de: "er/sie/es will", pl: "on/ona/ono chce" },
      { de: "wir wollen", pl: "my chcemy" },
      { de: "ihr wollt", pl: "wy chcecie" },
      { de: "sie wollen", pl: "oni/one chcą" }
    ]
  },
  basic_verbs_2: {
    labelDe: "Grundverben II (Konjugationen)",
    pairs: [
      { de: "ich kann (können)", pl: "ja mogę" },
      { de: "du kannst", pl: "ty możesz" },
      { de: "er/sie/es kann", pl: "on/ona/ono może" },
      { de: "wir können", pl: "my możemy" },
      { de: "ihr könnt", pl: "wy możecie" },
      { de: "sie können", pl: "oni/one mogą" },
      
      { de: "ich muss (müssen)", pl: "ja muszę" },
      { de: "du musst", pl: "ty musisz" },
      { de: "er/sie/es muss", pl: "on/ona/ono musi" },
      { de: "wir müssen", pl: "my musimy" },
      { de: "ihr müsst", pl: "wy musicie" },
      { de: "sie müssen", pl: "oni/one muszą" },
      
      { de: "ich mag (mögen)", pl: "ja lubię" },
      { de: "du magst", pl: "ty lubisz" },
      { de: "er/sie/es mag", pl: "on/ona/ono lubi" },
      { de: "wir mögen", pl: "my lubimy" },
      { de: "ihr mögt", pl: "wy lubicie" },
      { de: "sie mögen", pl: "oni/one lubią" },
      
      { de: "ich denke (denken)", pl: "ja myślę" },
      { de: "du denkst", pl: "ty myślisz" },
      { de: "er/sie/es denkt", pl: "on/ona/ono myśli" },
      { de: "wir denken", pl: "my myślimy" },
      { de: "ihr denkt", pl: "wy myślicie" },
      { de: "sie denken", pl: "oni/one myślą" },
      
      { de: "ich verstehe (verstehen)", pl: "ja rozumiem" },
      { de: "du verstehst", pl: "ty rozumiesz" },
      { de: "er/sie/es versteht", pl: "on/ona/ono rozumie" },
      { de: "wir verstehen", pl: "my rozumiemy" },
      { de: "ihr versteht", pl: "wy rozumiecie" },
      { de: "sie verstehen", pl: "oni/one rozumieją" },
      
      { de: "ich gebe (geben)", pl: "ja daję" },
      { de: "du gibst", pl: "ty dajesz" },
      { de: "er/sie/es gibt", pl: "on/ona/ono daje" },
      { de: "wir geben", pl: "my dajemy" },
      { de: "ihr gebt", pl: "wy dajecie" },
      { de: "sie geben", pl: "oni/one dają" },
      
      { de: "ich nehme (nehmen)", pl: "ja biorę" },
      { de: "du nimmst", pl: "ty bierzesz" },
      { de: "er/sie/es nimmt", pl: "on/ona/ono bierze" },
      { de: "wir nehmen", pl: "my bierzemy" },
      { de: "ihr nehmt", pl: "wy bierzecie" },
      { de: "sie nehmen", pl: "oni/one biorą" },
      
      { de: "ich lese (lesen)", pl: "ja czytam" },
      { de: "du liest", pl: "ty czytasz" },
      { de: "er/sie/es liest", pl: "on/ona/ono czyta" },
      { de: "wir lesen", pl: "my czytamy" },
      { de: "ihr lest", pl: "wy czytacie" },
      { de: "sie lesen", pl: "oni/one czytają" },
      
      { de: "ich schreibe (schreiben)", pl: "ja piszę" },
      { de: "du schreibst", pl: "ty piszesz" },
      { de: "er/sie/es schreibt", pl: "on/ona/ono pisze" },
      { de: "wir schreiben", pl: "my piszemy" },
      { de: "ihr schreibt", pl: "wy piszecie" },
      { de: "sie schreiben", pl: "oni/one piszą" },
      
      { de: "ich schlafe (schlafen)", pl: "ja śpię" },
      { de: "du schläfst", pl: "ty śpisz" },
      { de: "er/sie/es schläft", pl: "on/ona/ono śpi" },
      { de: "wir schlafen", pl: "my śpimy" },
      { de: "ihr schlaft", pl: "wy śpicie" },
      { de: "sie schlafen", pl: "oni/one śpią" }
    ]
  },
  basic_verbs_1_past: {
    labelDe: "Grundverben I (Vergangenheit)",
    pairs: [
      { de: "ich war (sein)", pl: "ja byłem / byłam" },
      { de: "du warst", pl: "ty byłeś / byłaś" },
      { de: "er war", pl: "on był" },
      { de: "sie war", pl: "ona była" },
      { de: "es war", pl: "ono było" },
      { de: "wir waren", pl: "my byliśmy / byłyśmy" },
      { de: "ihr wart", pl: "wy byliście / byłyście" },
      { de: "sie waren (m)", pl: "oni byli" },
      { de: "sie waren (f/n)", pl: "one były" },
      
      { de: "ich hatte (haben)", pl: "ja miałem / miałam" },
      { de: "du hattest", pl: "ty miałeś / miałaś" },
      { de: "er hatte", pl: "on miał" },
      { de: "sie hatte", pl: "ona miała" },
      { de: "es hatte", pl: "ono miało" },
      { de: "wir hatten", pl: "my mieliśmy / miałyśmy" },
      { de: "ihr hattet", pl: "wy mieliście / miałyście" },
      { de: "sie hatten (m)", pl: "oni mieli" },
      { de: "sie hatten (f/n)", pl: "one miały" },
      
      { de: "ich machte (machen)", pl: "ja robiłem / robiłam" },
      { de: "du machtest", pl: "ty robiłeś / robiłaś" },
      { de: "er machte", pl: "on robił" },
      { de: "sie machte", pl: "ona robiła" },
      { de: "es machte", pl: "ono robiło" },
      { de: "wir machten", pl: "my robiliśmy / robiłyśmy" },
      { de: "ihr machtet", pl: "wy robiliście / robiłyście" },
      { de: "sie machten (m)", pl: "oni robili" },
      { de: "sie machten (f/n)", pl: "one robiły" },
      
      { de: "ich ging (gehen)", pl: "ja szedłem / szłam" },
      { de: "du gingst", pl: "ty szedłeś / szłaś" },
      { de: "er ging", pl: "on szedł" },
      { de: "sie ging", pl: "ona szła" },
      { de: "es ging", pl: "ono szło" },
      { de: "wir gingen", pl: "my szliśmy / szłyśmy" },
      { de: "ihr gingt", pl: "wy szliście / szłyście" },
      { de: "sie gingen (m)", pl: "oni szli" },
      { de: "sie gingen (f/n)", pl: "one szły" },
      
      { de: "ich aß (essen)", pl: "ja jadłem / jadłam" },
      { de: "du aßest", pl: "ty jadłeś / jadłaś" },
      { de: "er aß", pl: "on jadł" },
      { de: "sie aß", pl: "ona jadła" },
      { de: "es aß", pl: "ono jadło" },
      { de: "wir aßen", pl: "my jedliśmy / jadłyśmy" },
      { de: "ihr aßt", pl: "wy jedliście / jadłyście" },
      { de: "sie aßen (m)", pl: "oni jedli" },
      { de: "sie aßen (f/n)", pl: "one jadły" },
      
      { de: "ich trank (trinken)", pl: "ja piłem / piłam" },
      { de: "du trankst", pl: "ty piłeś / piłaś" },
      { de: "er trank", pl: "on pił" },
      { de: "sie trank", pl: "ona piła" },
      { de: "es trank", pl: "ono piło" },
      { de: "wir tranken", pl: "my piliśmy / piłyśmy" },
      { de: "ihr trankt", pl: "wy piliście / piłyście" },
      { de: "sie tranken (m)", pl: "oni pili" },
      { de: "sie tranken (f/n)", pl: "one piły" },
      
      { de: "ich sprach (sprechen)", pl: "ja mówiłem / mówiłam" },
      { de: "du sprachst", pl: "ty mówiłeś / mówiłaś" },
      { de: "er sprach", pl: "on mówił" },
      { de: "sie sprach", pl: "ona mówiła" },
      { de: "es sprach", pl: "ono mówiło" },
      { de: "wir sprachen", pl: "my mówiliśmy / mówiłyśmy" },
      { de: "ihr spracht", pl: "wy mówiliście / mówiłyście" },
      { de: "sie sprachen (m)", pl: "oni mówili" },
      { de: "sie sprachen (f/n)", pl: "one mówiły" },
      
      { de: "ich wusste (wissen)", pl: "ja wiedziałem / wiedziałam" },
      { de: "du wusstest", pl: "ty wiedziałeś / wiedziałaś" },
      { de: "er wusste", pl: "on wiedział" },
      { de: "sie wusste", pl: "ona wiedziała" },
      { de: "es wusste", pl: "ono wiedziało" },
      { de: "wir wussten", pl: "my wiedzieliśmy / wiedziałyśmy" },
      { de: "ihr wusstet", pl: "wy wiedzieliście / wiedziałyście" },
      { de: "sie wussten (m)", pl: "oni wiedzieli" },
      { de: "sie wussten (f/n)", pl: "one wiedziały" },
      
      { de: "ich sah (sehen)", pl: "ja widziałem / widziałam" },
      { de: "du sahst", pl: "ty widziałeś / widziałaś" },
      { de: "er sah", pl: "on widział" },
      { de: "sie sah", pl: "ona widziała" },
      { de: "es sah", pl: "ono widziało" },
      { de: "wir sahen", pl: "my widzieliśmy / widziałyśmy" },
      { de: "ihr saht", pl: "wy widzieliście / widziałyście" },
      { de: "sie sahen (m)", pl: "oni widzieli" },
      { de: "sie sahen (f/n)", pl: "one widziały" },
      
      { de: "ich wollte (wollen)", pl: "ja chciałem / chciałam" },
      { de: "du wolltest", pl: "ty chciałeś / chciałaś" },
      { de: "er wollte", pl: "on chciał" },
      { de: "sie wollte", pl: "ona chciała" },
      { de: "es wollte", pl: "ono chciało" },
      { de: "wir wollten", pl: "my chcieliśmy / chciałyśmy" },
      { de: "ihr wolltet", pl: "wy chcieliście / chciałyście" },
      { de: "sie wollten (m)", pl: "oni chcieli" },
      { de: "sie wollten (f/n)", pl: "one chciały" }
    ]
  },
  basic_verbs_2_past: {
    labelDe: "Grundverben II (Vergangenheit)",
    pairs: [
      { de: "ich konnte (können)", pl: "ja mogłem / mogłam" },
      { de: "du konntest", pl: "ty mogłeś / mogłaś" },
      { de: "er konnte", pl: "on mógł" },
      { de: "sie konnte", pl: "ona mogła" },
      { de: "es konnte", pl: "ono mogło" },
      { de: "wir konnten", pl: "my mogliśmy / mogłyśmy" },
      { de: "ihr konntet", pl: "wy mogliście / mogłyście" },
      { de: "sie konnten (m)", pl: "oni mogli" },
      { de: "sie konnten (f/n)", pl: "one mogły" },
      
      { de: "ich musste (müssen)", pl: "ja musiałem / musiałam" },
      { de: "du musstest", pl: "ty musiałeś / musiałaś" },
      { de: "er musste", pl: "on musiał" },
      { de: "sie musste", pl: "ona musiała" },
      { de: "es musste", pl: "ono musiało" },
      { de: "wir mussten", pl: "my musieliśmy / musiałyśmy" },
      { de: "ihr musstet", pl: "wy musieliście / musiałyście" },
      { de: "sie mussten (m)", pl: "oni musieli" },
      { de: "sie mussten (f/n)", pl: "one musiały" },
      
      { de: "ich mochte (mögen)", pl: "ja lubiłem / lubiłam" },
      { de: "du mochtest", pl: "ty lubiłeś / lubiłaś" },
      { de: "er mochte", pl: "on lubił" },
      { de: "sie mochte", pl: "ona lubiła" },
      { de: "es mochte", pl: "ono lubiło" },
      { de: "wir mochten", pl: "my lubiliśmy / lubiłyśmy" },
      { de: "ihr mochtet", pl: "wy lubiliście / lubiłyście" },
      { de: "sie mochten (m)", pl: "oni lubili" },
      { de: "sie mochten (f/n)", pl: "one lubiły" },
      
      { de: "ich dachte (denken)", pl: "ja myślałem / myślałam" },
      { de: "du dachtest", pl: "ty myślałeś / myślałaś" },
      { de: "er dachte", pl: "on myślał" },
      { de: "sie dachte", pl: "ona myślała" },
      { de: "es dachte", pl: "ono myślało" },
      { de: "wir dachten", pl: "my myśleliśmy / myślałyśmy" },
      { de: "ihr dachtet", pl: "wy myśleliście / myślałyście" },
      { de: "sie dachten (m)", pl: "oni myśleli" },
      { de: "sie dachten (f/n)", pl: "one myślały" },
      
      { de: "ich verstand (verstehen)", pl: "ja rozumiałem / rozumiałam" },
      { de: "du verstandst", pl: "ty rozumiałeś / rozumiałaś" },
      { de: "er verstand", pl: "on rozumiał" },
      { de: "sie verstand", pl: "ona rozumiała" },
      { de: "es verstand", pl: "ono rozumiało" },
      { de: "wir verstanden", pl: "my rozumieliśmy / rozumiałyśmy" },
      { de: "ihr verstandet", pl: "wy rozumieliście / rozumiałyście" },
      { de: "sie verstanden (m)", pl: "oni rozumieli" },
      { de: "sie verstanden (f/n)", pl: "one rozumiały" },
      
      { de: "ich gab (geben)", pl: "ja dawałem / dawałam" },
      { de: "du gabst", pl: "ty dawałeś / dawałaś" },
      { de: "er gab", pl: "on dawał" },
      { de: "sie gab", pl: "ona dawała" },
      { de: "es gab", pl: "ono dawało" },
      { de: "wir gaben", pl: "my dawaliśmy / dawałyśmy" },
      { de: "ihr gabt", pl: "wy dawaliście / dawałyście" },
      { de: "sie gaben (m)", pl: "oni dawali" },
      { de: "sie gaben (f/n)", pl: "one dawały" },
      
      { de: "ich nahm (nehmen)", pl: "ja brałem / brałam" },
      { de: "du nahmst", pl: "ty brałeś / brałaś" },
      { de: "er nahm", pl: "on brał" },
      { de: "sie nahm", pl: "ona brała" },
      { de: "es nahm", pl: "ono brało" },
      { de: "wir nahmen", pl: "my braliśmy / brałyśmy" },
      { de: "ihr nahmt", pl: "wy braliście / brałyście" },
      { de: "sie nahmen (m)", pl: "oni brali" },
      { de: "sie nahmen (f/n)", pl: "one brały" },
      
      { de: "ich las (lesen)", pl: "ja czytałem / czytałam" },
      { de: "du last", pl: "ty czytałeś / czytałaś" },
      { de: "er las", pl: "on czytał" },
      { de: "sie las", pl: "ona czytała" },
      { de: "es las", pl: "ono czytało" },
      { de: "wir lasen", pl: "my czytaliśmy / czytałyśmy" },
      { de: "ihr last", pl: "wy czytaliście / czytałyście" },
      { de: "sie lasen (m)", pl: "oni czytali" },
      { de: "sie lasen (f/n)", pl: "one czytały" },
      
      { de: "ich schrieb (schreiben)", pl: "ja pisałem / pisałam" },
      { de: "du schriebst", pl: "ty pisałeś / pisałaś" },
      { de: "er schrieb", pl: "on pisał" },
      { de: "sie schrieb", pl: "ona pisała" },
      { de: "es schrieb", pl: "ono pisało" },
      { de: "wir schrieben", pl: "my pisaliśmy / pisałyśmy" },
      { de: "ihr schriebet", pl: "wy pisaliście / pisałyście" },
      { de: "sie schrieben (m)", pl: "oni pisali" },
      { de: "sie schrieben (f/n)", pl: "one pisały" },
      
      { de: "ich schlief (schlafen)", pl: "ja spałem / spałam" },
      { de: "du schliefst", pl: "ty spałeś / spałaś" },
      { de: "er schlief", pl: "on spał" },
      { de: "sie schlief", pl: "ona spała" },
      { de: "es schlief", pl: "ono spało" },
      { de: "wir schliefen", pl: "my spaliśmy / spałyśmy" },
      { de: "ihr schlieft", pl: "wy spaliście / spałyście" },
      { de: "sie schliefen (m)", pl: "oni spali" },
      { de: "sie schliefen (f/n)", pl: "one spały" }
    ]
  }
};
